accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# mysite.urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path as url
from django.views.static import serve
urlpatterns = [
    path('rwulfi/', admin.site.urls),
    path('', include('wulfi.urls', namespace='wulfi')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

wulfi/urls.py
from django.urls import path
from . import views

app_name = 'wulfi'

urlpatterns = [
    path('', views.home, name='home'),

    path('posts/', views.posts, name='posts'),
    path('projects/', views.projects, name='projects'),
    path('project/<str:pk>/', views.viewProject, name='project'),
    
    path('about/', views.about, name='about'),
    # path('contact/', views.contact, name='contact'),
    path('<slug:post>/', views.post, name='post'),
    # path("like/<int:pk>", views.likeView, name="like_post"),


    # ### API ###
    path('api/routes/', views.getRoutes),
    path('api/posts/', views.getPosts),
    path('api/posts/<str:pk>/', views.getPost),
    
]

wulfi/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class Profile(models.Model):

    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="profile")
    bio = models.TextField(null=True, blank=True)
    twitter = models.URLField(max_length=200,null=True, blank=True)
    profile_views = models.IntegerField(default=0, null=True, blank=True)


    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        name = str(self.first_name)
        if self.last_name:
            name += ' ' + str(self.last_name)
        return name


class PostManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):

    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='author')

    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="post", default="placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)
    post_views = models.IntegerField(default=0, null=True, blank=True)
    # likes = models.ManyToManyField(User, blank=True, related_name='likes')
    # dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')

    updated = models.DateTimeField(auto_now=True)

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    
    status = models.CharField(max_length=10, choices=options, default='draft')

    objects = models.Manager()  # default manager
    postmanager = PostManager()  # custom manager  # articlemanager = PostManager()

    def get_absolute_url(self):
        return reverse('wulfi:post', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.headline

class Project(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=500)
    image = models.ImageField(null=True, blank=True)
    category = models.ManyToManyField(Tag, blank=True)
    description = models.TextField()
    link = models.URLField(max_length=200,null=True, blank=True)
    # post_views = models.IntegerField(default=0, null=True, blank=True)


    def __str__(self):
        return self.title

# class Comment(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
#     name = models.CharField(max_length=255)
#     body = models.TextField()
#     date_added = models.DateTimeField(auto_now=True) 

#     def __str__(self):
#         return '%s - %s' % (self.post.title, self.name)


class Banner(models.Model):
    title = models.CharField(max_length=255, blank=True)
    greeting = models.CharField(max_length=255, blank=True)    
    body = models.TextField()
    date_added = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.title

wulfi/forms.py
# from django.forms import ModelForm

# from .models import Comment

# class CommentForm(ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['name', 'body']

wulfi/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, Tag, Profile, Project, Banner  #, Comment
from django.contrib.auth.models import auth
# Django Q objects use to create complex queries
from django.db.models import Q
import random
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
import time

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# from .forms import CommentForm

def home(request):
    # get query from request
    query = request.GET.get('query')
    # print(query)
    # Set query to '' if None
    if query == None:
        query = ''

    # posts = Post.postmanager.all()
    # search for query in headline, sub headline, body
    posts = Post.postmanager.filter(
        Q(headline__icontains=query) |
        Q(sub_headline__icontains=query) |
        Q(body__icontains=query)
    )

    # feature posts on the home page
    featured = Post.postmanager.filter(featured=True)[0:3]

    # To access latest updated profile image, Profile is a Profile table inside the models
    profiles = Profile.objects.latest('updated')
    profiles.profile_views = profiles.profile_views + 1
    profiles.save() 

    banner = Banner.objects.latest('date_added')
    # To display tags for searching categies
    tags = Tag.objects.all()

    listtags = list(tags)

    # To display tags randomly for searching by tags
    randomtags = random.sample(listtags, 4)

    category = request.GET.get('category')

    if category == None:
        projects = Project.objects.all()[0:3]

    else:
        projects = Project.objects.filter(category__name=category)

    categories = Tag.objects.all()

    "#Number of visits to this view, as counted in the session variable."
    # num_visits = request.session.get('num_visits', 1)
    # request.session['num_visits'] = num_visits + 1

    # Pass the context so that we can access inside the rendered template
    context = {
        'posts': posts,
        'featured': featured,
        'tags': tags,
        'randomtags': randomtags,
        'profiles': profiles,
        'banner': banner,
        'query': query,
        'projects': projects,
        'categories': categories,
        'categoryname': category,
    }  
    # 'count': num_visits,
    # 

    return render(request, 'index.html', context)


def post(request, post):

    post = get_object_or_404(Post, slug=post, status='published')
    post.post_views = post.post_views + 1
    post.save()
    # time.sleep(2)
    
    profiles = Profile.objects.latest('updated') 
    banner = Banner.objects.latest('date_added')
    

    context = {
        'post': post,
        'profiles': profiles,
        'banner': banner,
        
    }
    



    # if request.method == 'POST':
    #     form = CommentForm(request.POST)

    #     if form.is_valid():
    #         obj = form.save(commit=False)
    #         obj.post = post
    #         obj.save()
    #         context.update({'form': form, 'slug':post.slug})

    #         # return redirect('post', slug=post.slug)
    #         return render(request, 'Post.html', context)
    # else:
    #     form = CommentForm()
    #     context.update({'form': form})

    return render(request, 'Post.html', context)

def posts(request):
    # get query from request
    query = request.GET.get('query')
    # print(query)
    # Set query to '' if None
    if query == None:
        query = ''

    # posts = Post.postmanager.all()
    # search for query in headline, sub headline, body
    posts = Post.postmanager.filter(
        Q(headline__icontains=query) |
        Q(sub_headline__icontains=query) |
        Q(body__icontains=query)
    )

    # results = True
    # if posts == None:
    #     results = False

    profiles = Profile.objects.latest('updated') 
    banner = Banner.objects.latest('date_added')
    

    tags = Tag.objects.all()
    
    listtags = list(tags)

    # To display tags randomly for searching by tags
    randomtags = random.sample(listtags, 5)

    context = {
        'posts': posts,
        # 'slug': post.slug,
        'tags': tags,
        'query': query,
        'randomtags': randomtags,
        'profiles': profiles,
        'banner': banner,
        
    }

    return render(request, 'Posts.html', context)


def projects(request):
    # get query from request
    query = request.GET.get('query')
    # print(query)
    # Set query to '' if None
    if query == None:
        query = ''

    # posts = Post.postmanager.all()
    # search for query in headline, sub headline, body
    posts = Post.postmanager.filter(
        Q(headline__icontains=query) |
        Q(sub_headline__icontains=query) |
        Q(body__icontains=query)
    )

    # feature posts on the home page
    featured = Post.postmanager.filter(featured=True)[0:3]

    # To access latest updated profile image, Profile is a Profile table inside the models
    profiles = Profile.objects.latest('updated')
    profiles.profile_views = profiles.profile_views + 1
    profiles.save() 

    banner = Banner.objects.latest('date_added')
    # To display tags for searching categies
    tags = Tag.objects.all()

    listtags = list(tags)

    # To display tags randomly for searching by tags
    randomtags = random.sample(listtags, 4)

    category = request.GET.get('category')

    if category == None:
        projects = Project.objects.all()

    else:
        projects = Project.objects.filter(category__name=category)

    categories = Tag.objects.all()

    "#Number of visits to this view, as counted in the session variable."
    # num_visits = request.session.get('num_visits', 1)
    # request.session['num_visits'] = num_visits + 1

    # Pass the context so that we can access inside the rendered template
    context = {
        'posts': posts,
        'featured': featured,
        'tags': tags,
        'randomtags': randomtags,
        'profiles': profiles,
        'banner': banner,
        'query': query,
        'projects': projects,
        'categories': categories,
        'categoryname': category,
    }  
    # 'count': num_visits,
    # 

    return render(request, 'project.html', context)

def viewProject(request, pk):
    project = Project.objects.get(id=pk)
    profiles = Profile.objects.latest('updated') 
    banner = Banner.objects.latest('date_added')

    context = {
        'profiles': profiles,
        'banner': banner,
        'project': project
        
    }
    return render(request, 'projectDetail.html', context)
    
def about(request):

    profiles = Profile.objects.latest('updated') 
    banner = Banner.objects.latest('date_added')

    context = {
        'profiles': profiles,
        'banner': banner,
        
    }

    ## Allow Less secure app access on gmail

    if request.method == "POST":

        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        
        # send_mail(
        #     'Contact form', 
        #     message, 
        #     settings.EMAIL_HOST_USER, 
        #     ['wulficode@gmail.com'], 
        #     fail_silently=False
        # )
    
        data = {
            'name': name,
            'email': email,
            'message': message
        }
        message = '''
        New message: {}
        By: {}
        From: {}
        '''.format(data['message'], data['name'], data['email'])

        # send an email
        try:
            if name is None or email is None or message is None:
                messages.info(request, 'Enter all the details')
                return render(request, 'about.html', context)

                
            else:
                send_mail(data['message'], message, '', ['email@gmail.com',], fail_silently=False)
                messages.info(request, 'Message sent')
                # context.update({'profiles': profiles})
                return render(request, 'about.html', context)
        except:
            messages.info(request, 'Could not sent your message')
            # context.update({'profiles': profiles})
            # return render(request, 'contact.html', context)
        
    return render(request, 'about.html', context)

# def contact(request):

#     profiles = Profile.objects.latest('updated') 

#     if request.method == "POST":

#         name = request.POST['name']
#         email = request.POST['email']
#         message = request.POST['message']
    
#         data = {
#             'name': name,
#             'email': email,
#             'message': message
#         }
#         message = '''
#         New message: {}
#         By: {}
#         From: {}
#         '''.format(data['message'], data['name'], data['email'])

#         # send an email
#         try:
#             send_mail(data['message'], message, '', ['wulficode@gmail.com'], fail_silently=False)
#             messages.info(request, 'Message sent')
#             context = {'profiles': profiles}
#             return render(request, 'contact.html', context)
#         except:
#             messages.info(request, 'Could not sent your message')
#             context = {'profiles': profiles}
#             return render(request, 'contact.html', context)
    
#     return render(request, 'contact.html', {'profiles': profiles})




############# API VIEWS ##################

from rest_framework.decorators import api_view
from rest_framework.response import Response

from .serializers import PostSerializer
from .models import Profile, Tag, Post, Project


@api_view(['GET']) # 'GET' decorator
def getRoutes(request):  # function based view 
    routes = [
        {
            'Endpoint': 'api/routes/',
            'method': 'Get',
            'body': None,
            'description': 'Return all the routes'
        },
        {
            'Endpoint': 'api/posts/id/',

wulfi/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ===== Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- =====BOX ICONS===== -->
    <!-- <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'> -->
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>


    <!--==================== CSS ====================-->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}">


    <title>{% block title %}{% endblock %}</title>
    {% block stl %}{% endblock %}

</head>

<body>
    <!--==================== HEADER ====================-->
    <header class="l-header" id="header">
        <nav class="nav bd-grid">
            <div>
                <a href="{% url 'wulfi:home' %}" class="nav__logo"><h4><b>John</b></h4></a>
            </div>
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list">

                    {% block nav %} {% endblock %}

                </ul>
            </div>

            <div class="nav_btns">
                <!-- Theme change button -->
                <i class="bx bx-moon" id="icon"></i>
                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>

            </div>
        </nav>

    </header>

    <!--==================== MAIN ====================-->
    <main class="l-main">
        <!--==================== HOME ====================-->

        <section class="home section" id="home">

            <div class="home__container bd-grid">
                <div class="home__img">
                    <svg class="home_blob" viewBox="0 0 200 187" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <mask id="mask0" mask-type="alpha">
                                <path class="blob_fill_color" d="M51,-67.9C62.9,-61.5,67.2,-42.4,67.5,-25.7C67.8,-8.9,64.1,5.4,58.9,18.4C53.6,31.4,46.8,43.2,36.7,53.2C26.6,63.2,13.3,71.6,0.9,70.3C-11.5,69.1,-23,58.4,-31.3,47.7C-39.5,37.1,-44.4,26.5,-49.5,15.1C-54.6,3.6,-59.9,-8.8,-58.4,-20.6C-56.8,-32.5,-48.4,-43.8,-37.5,-50.4C-26.7,-57.1,-13.3,-59.2,3.1,-63.4C19.5,-67.7,39.1,-74.2,51,-67.9Z" transform="translate(100 100)" />
                            </mask>
                            <g mask="url(#mask0)">
                                <path class="blob_fill_color" d="M51,-67.9C62.9,-61.5,67.2,-42.4,67.5,-25.7C67.8,-8.9,64.1,5.4,58.9,18.4C53.6,31.4,46.8,43.2,36.7,53.2C26.6,63.2,13.3,71.6,0.9,70.3C-11.5,69.1,-23,58.4,-31.3,47.7C-39.5,37.1,-44.4,26.5,-49.5,15.1C-54.6,3.6,-59.9,-8.8,-58.4,-20.6C-56.8,-32.5,-48.4,-43.8,-37.5,-50.4C-26.7,-57.1,-13.3,-59.2,3.1,-63.4C19.5,-67.7,39.1,-74.2,51,-67.9Z" transform="translate(100 100)" />
                                <a href="{% url 'wulfi:home' %}"><image class="about_blob-img" x="40" y="18" xlink:href="{% static 'assets/img/profile-pic.png' %}"/> </a>
                                
                            </g>
                        </svg>
                </div>

                <div class="home_social_box">
                    <a href="{% url 'wulfi:home' %}">
                        <h2 class="home__subtitle">John</h2>
                    </a>

                    <div class="home__social">
                        
                        <a href="https://github.com" target="_blank" class="home__social-icon"><i class='bx bxl-github'></i></a>

                        <a href="{{ profiles.twitter }}" target="_blank" class="home__social-icon"><i class='bx bxl-twitter' ></i></a>
                        <a href="https://www.linkedin.com/" target="_blank" class="home__social-icon"><i class='bx bxl-linkedin-square'></i></a>

                    </div>

                </div>

            </div>


        </section>

        <section class="section">

            <div class="Box">
                <div class="Inner_Box">

                    <h1 class="bannergreeting">{{ banner.greeting }}</h1>

                    <p class="bannerbody">{{ banner.body }} </p>

                </div>

            </div>
            


        </section>

        <!-- =============  BLOCK CONTENT ======== -->
        {% block content %} {% endblock %}
        <div class="sp" style="text-align: center; margin-top: 5rem; visibility: hidden;">
        </div>

    </main>

    <!--==================== FOOTER ====================-->
    <footer class="footer">
        <div class="footer__login_box">

            {% if request.user.is_authenticated %}
            <p>Hello, {{request.user}}</p>
            <a href="{% url 'accounts:logout' %}" class="login_link">Logout</a> {% else %}
            <a href="{% url 'accounts:register' %}" class="login_link">Register</a>
            <a href="{% url 'accounts:login' %}" class="login_link">Login</a>{% endif %}
        </div>

        <p class="footer__title">John</p>
        <div class="footer__social">
            
            <a href="https://github.com" target="_blank" class="footer__icon"><i class='bx bxl-github'></i></a>
            
            <a href="#" target="_blank" class="footer__icon"><i class='bx bxl-twitter' ></i></a>

            <a href="https://www.linkedin.com" target="_blank" class="footer__icon"><i class='bx bxl-linkedin-square'></i></a>

        </div>

        <div class="footer__data">
            <p class="footer__explore">Explore</p>
            <ul>
                <li><a href="{% url 'wulfi:home' %}" class="footer__link">Home</a></li>
                <li><a href="{% url 'wulfi:posts' %}" class="footer__link">Posts</a></li>
                <li><a href="{% url 'wulfi:projects' %}#project" class="footer__link">Works</a></li>
                <li><a href="{% url 'wulfi:about' %}" class="footer__link">About</a></li>
            </ul>
        </div>

        <p class="footer_copy_right">Copyright &#169; 2022 John. </p>


    </footer>

    <!--===== SCROLL REVEAL =====-->
    <script src="https://unpkg.com/scrollreveal"></script>
    <!---JS CDN Link-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!--==================== MAIN JS ====================-->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

wulfi/templates/contact.html
{% extends "base.html" %} {% load static %} {% block title %} John: Contact {% endblock %} {% block nav %}
<li class="nav__item"><a href="{% url 'wulfi:home' %}" class="nav__link">Home</a></li>
<li class="nav__item"><a href="{% url 'wulfi:posts' %}" class="nav__link">Posts</a></li>
<li class="nav__item"><a href="{% url 'wulfi:about' %}" class="nav__link">About</a></li>
<li class="nav__item"><a href="{% url 'wulfi:contact' %}" class="nav__link active">Contact</a></li>
{% endblock %}
<!-- {% block img %}
<image class="home_blob-img" x="40" y="18" xlink:href="{{ profiles.profile_pic.url }}" />{% endblock %}  -->
{% block content %}
<!--==================== CONTACT ME ====================-->
<section class="contact section" id="contact">
    <h2 class="section-title">Contact</h2>

    <div class="contact__container bd-grid">
        <p class="contact_message">Let us get in touch and help each other!</p>

        <div class="contact__info">
            <h3 class="contact__subtitle">EMAIL</h3>
            <span class="contact__text">info.mail.com</span>

            <h3 class="contact__subtitle">PHONE</h3>
            <span class="contact__text">+10 555-999</span>

            <h3 class="contact__subtitle">ADDRESS</h3>
            <span class="contact__text">Bhutan</span>
        </div>

        {% for message in messages %}
        <p class="message_sent">{{ message }}</p>
        {% endfor %}

        <form action="{% url 'wulfi:contact' %}" method="post" class="contact__form">
            {% csrf_token %}
            <input type="name" name="name" placeholder="Name" class="contact__input">
            <input type="email" name="email" placeholder="Email" class="contact__input">
            <textarea name="message" id="" placeholder="Enter your message" cols="0" rows="10" class="contact__input"></textarea>
            <!-- <input type="button" value="Enter" class="contact__button button"> -->
            <button type="submit" class="contact__button button">Enter</button>
        </form>
    </div>
</section>
{% endblock %}

wulfi/templates/index.html
{% extends "base.html" %} {% load static %} {% block title %} John {% endblock %} 
{% block stl %}
<style type="text/css">
    .tweet-body {
        margin: 0;
        padding: 0;
        background: rgb(255, 255, 255);
        border-radius: 10px;
    }

    .scroll-bg {
        background: rgb(17, 17, 105);
        margin: 10% auto;
        padding: 30px;
        border-radius: 10px;
    }
    .scroll-div {
        background: rgb(17, 17, 105);
        height: 420px;
        overflow: hidden;
        overflow-y: scroll;
    }
    .scroll-object {
        color: wheat;
        padding: 20px;
    }
</style>
{% endblock %}
{% block nav %}
<li class="nav__item"><a href="{% url 'wulfi:home' %}" class="nav__link active">Home</a></li>
<li class="nav__item"><a href="{% url 'wulfi:posts' %}" class="nav__link" id="post">Posts</a></li>
<li class="nav__item"><a href="{% url 'wulfi:projects' %}#project" class="nav__link">Works</a></li>
<li class="nav__item"><a href="{% url 'wulfi:about' %}" class="nav__link">About</a></li>
{% endblock %}
<!-- {% block img %}

<image class="home_blob-img" x="40" y="18" xlink:href="{{ profiles.profile_pic.url }}" />{% endblock %}  -->
{% block content %}
<!--==================== EXPLORE ====================-->
<section class="explore section" id="explore">

    <div class="explore__container">

        <h3 class="explore-title" id="post">Explore Categories</h3>

        <div class="explore__box">
            <!-- for tag in tags -->
            {% for tag in randomtags %}
            <span class="explore__name"><a href="?query={{ tag }}" class="__link">{{ tag }}</a></span> {% endfor %}
        </div>

    </div>



</section>
<hr class="line bd-grid">


<!--==================== SEARCH POSTS BY CATEGORY ====================-->
<section class="featured" id="featured">
    <div class="featured__container bd-grid">

        <!-- If we search by using tags, show this -->
        {% if query %}
        <h2 class="explore-title">Results matching {{query}}</h2>

        <div class="featured-content">
            {% for post in posts %}
            <!-- item -->
            <div class="featured-item">
                <div class="featured-img">
                    <a href="{{ post.get_absolute_url }}">
                        <!-- <img src="{{post.image.url}}" alt=""> -->
                        <img src="{% static 'assets/img/work4.jpg' %}" alt="">
                        <span class="date"><i class='bx bx-calendar-star'></i>{{ post.publish|date:"M Y" }}</span>
                        <span class="post_subhead">{{ post.sub_headline }}</span>
                    </a>

                </div>
                <div class="featured-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.headline }}</a>
                </div>
            </div>
            <!-- end of item -->
            {% empty %}
            <p>No Results found...</p>

            {% endfor %}
        </div>
        {% endif %}
    </div>
</section>

<!--==================== FEATURED POSTS ====================-->
<section class="featured section" id="featured">
    <div class="featured__container bd-grid">
        <h2 class="section-title">Featured Posts</h2>

        <div class="featured-content">
            {% for post in featured %}
            <!-- item -->
            <div class="featured-item">
                <div class="featured-img">
                    <a href="{{ post.get_absolute_url }}">
                        <!-- <img src="{{post.image.url}}" alt=""> -->
                        <img src="{% static 'assets/img/work4.jpg' %}" alt="">
                        <span class="date"><i class='bx bx-calendar-star'></i>{{ post.publish|date:"M Y" }}</span>
                        <span class="post_subhead">{{ post.sub_headline }}</span>
                    </a>

                </div>
                <div class="featured-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.headline }}</a>
                </div>
            </div>
            <!-- end of item -->
            {% empty %}
            <h3>No Featured Posts at the Moment...</h3>

            {% endfor %}
        </div>

    </div>
</section>

<!-- Projects -->
<section class="project section" id="project">
    <div class="project__container bd-grid">
        {% if categoryname %}
        <h2 class="section-title">{{categoryname}} Projects</h2>
        {% else %}
        <h2 class="section-title">Projects</h2>
        {% endif %}
        <div class="row">

            <div class="col">
                <div class="row">

                    <div class="project-content col">
                        {% for project in projects %}

                        <div class="project-item card my-2">
                            <img class="image-thumbnail" src="{% static 'assets/img/portfolio2.jpg' %}" alt="Card image cap">

                            <div class="card-body">
                                <small style="color: black;">{{project.title}}</small>
                            </div>
                            <a href="{% url 'wulfi:project' project.id %}" class="btn btn-outline-dark btn-sm m-1">View</a>
                        </div>
                        {% empty %}
                        <h3>No projects yet...</h3>
                        {% endfor %}


                    </div>
                    


                </div>
            </div>

            {% comment %} <div class="col-md-3">
                <div class="category card">
                    <div class="card-header bg-secondary">
                        <p class="row text-uppercase text-white pt-2 justify-content-center">Categories</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'wulfi:home' %}">All</a>
                        </li>

                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'wulfi:home' %}?category={{category.name}}">
                        {{category.name}}
                    </a>
                        </li>
                        {% endfor %}

                        <!-- <a href="" class="btn btn-dark btn-block btn-sm m-1">Add Photo</a> -->

                    </ul>
                </div>
            </div> {% endcomment %}
        </div>
    </div>
</section>


<!--==================== ABOUT ====================-->
<section class="about section" id="about">
    <h2 class="section-title">Hey, I am John</h2>

    <div class="about__container bd-grid">
        <div class="about__img">
            <img src="{% static 'assets/img/testimonial1.png' %}" alt="image">
            
        </div>

        <div>

            <span class="about__profession"><h2 class="about__subtitle">College Student</h2></span>
            <p class="about__text">An API lover. I have a great passion for Back-End Development and programming in general because it allows me to be inquisitive and resourceful in my work. I'm constantly striving to better myself in this field so that I can one day reach the level of success that I dream of.<br><br><a href="{% url 'wulfi:about' %}" class="details_btn">more details</a></p>
            
        </div>
    </div>

</section>




{% endblock %}